# Generated by Django 4.1.4 on 2023-05-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='skill',
        ),
    ]
