# Generated by Django 4.1.4 on 2023-05-25 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contact_email_alter_contact_meesage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
