# Generated by Django 4.1.4 on 2023-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=55)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
